### ISSUE TITLE
Assumptions for Linear Regression

### ISSUE THREAD

**Issue by deannagould** [learn-co-curriculum/dsc-regression-assumptions-v2-5#1]
## Link to Canvas

https://learning.flatironschool.com/courses/5599/assignments/196604?module_item_id=443514

## Issue Subtype

Pairplot isn't working and some other things
- [ ] Master branch code
- [ ] Solution branch code
- [ ] Code tests
- [ ] Layout/rendering issue
- [ ] Instructions unclear
- [ ] Other (explain below)

### Source

```

```

## (Optional) Proposed Solution

stay with illumidesk

## What OS Are You Using?

- [ X] OS X
- [ ] Windows
- [ ] WSL
- [ ] Linux
- [ ] IllumiDesk
- [X] Saturn Cloud

**Comment by jessepisel** [comment]
Thanks for opening this issue @deannagould :wave:. This error is coming from a conflict between `Seaborn` and `Matplotlib`. 

You can upgrade matplotlib to v3.6.2 by running the following command in a notebook cell `pip install matplotlib --upgrade` or you can downgrade matplotlib by running the following command in a notebooks cell `pip install matplotlib==3.6.0 --force-reinstall`.

After running one of those two commands, restart the kernel and re-run all the notebook cells. I was able to get it working on SaturnCloud with the upgrade method. Please let me know what questions you have.
